### ISSUE TITLE
hyperlink shows with extra slashes

### ISSUE THREAD

**Issue by fanzeyi** [markbt/streampager#57]
Reproduce:

```
$ cat test.py
print("\x1b]8;;{link}\x1b\\{title}\x1b]8;;\x1b\\".format(link="http://example.com/", title="example"))

$ python test.py
```

<img width="307" alt="image" src="https://user-images.githubusercontent.com/409951/181137728-bacb3b9b-715e-4db6-a230-8986fb025fd1.png">

```
$ python test.py | sp
```
<img width="253" alt="image" src="https://user-images.githubusercontent.com/409951/181137900-320ab8cb-e7f5-4849-b7dc-62647d395be4.png">

```
$ python test.py | less -r
```
<img width="215" alt="image" src="https://user-images.githubusercontent.com/409951/181137892-2a8ceba5-22d2-44e2-8b48-9a954fe27985.png">

**Comment by markbt** [comment]
It looks like the cause is from the underlying `vtparse` library, notably this comment:

https://github.com/wez/wezterm/blob/main/vtparse/src/lib.rs#L808-L812
>   // This case isn't the same as the other OSC cases; even though
>   // `ESC \` is the long form escape sequence for ST, the ESC on its
>   // own breaks out of the OSC state and jumps into the ESC state,
>   // and that leaves the `\` character to be dispatched there in
>   // the calling application.

I'm not sure how I'm supposed to tell the difference between `OSC 8 ; ; BEL \` and `OSC 8 ; ; ESC \`, as these will both return `[ SetHyperlink, Char('\') ]` even though the latter one (and only the latter one) should swallow the `\`.  Maybe @wez may know.

**Comment by wez** [comment]
I haven't looked too deeply at this specific case, but a quick glance at the test case you linked where `ESC \` (aka: `ST`) is emitted; that should be OK to handle in your application by simply ignoring it.
If the ESC is being lost, that sounds like a bug.
Which part of the termwiz API are you calling in to?

**Comment by wez** [comment]
I added some test cases with snapshots to see what is being returned, and it looks correct to me.
What I think you want to do is add a case in the match statement over here:

https://github.com/markbt/streampager/blob/df65f0e1158d496595c594ae3d1533418f8cc04b/src/line.rs#L535-L539

that filters out the `Esc::Code(StringTerminator)`.

That escape is never printable and its effects are already modeled by the underlying parser (by terminating the OSC string state), so it is completely valid to ignore it. Yes, this does feel surprising! I think that's the only case like this in vtparse.

**Comment by markbt** [comment]
It's not quite that simple.

First off, as a general-purpose pager, I don't really want to be in the business of swallowing arbitrary sequences.  If a file genuinely contains a rogue `ESC \` I want to see that in the output as **`<1B>`**`\`.

But the real problem is that I don't use the same `Parser` for the whole sequence.  I only use the parsers for when I am parsing escape sequence.  For other text I parse it myself so that I can detect and manage other things (like search matches).  This sequence causes `parse_first_as_vec` to return an offset value that is *in the middle* of the `ESC \` sequence, which is not useful for what streampager is trying to do (slice the line up into spans), and also leaves the parser in a non-ground state (`Escape`), which means resuming from the resulting offset with a new `Parser` doesn't do the right thing.

Ideally the parser would handle `ESC \` rather than doing this, but I think we can make it work by tightening up the contract for `parse_first_as_vec` to include the requirement that it returns the state machine back to the ground state, i.e. the state machine doesn't have any lingering state.

I've put up a suggestion of what I mean in this commit: https://github.com/wez/wezterm/commit/d7d055b979735b54b6b7cd1758fb340ce176be6e

There's also a test addition to show that the offsets returned correctly cover the full sequence.  Without this, the slices are a byte short.

With that, streampager renders hyperlinks correctly, and also correctly handles rogue `ESC \` sequences in the input.

**Comment by wez** [comment]
I see; that makes sense. Want to send a PR for that change?
